# Generated by Django 4.1.7 on 2023-03-15 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='subtraction_logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_number', models.IntegerField()),
                ('second_number', models.IntegerField()),
                ('result', models.IntegerField(default=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
